#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [[ "$OSTYPE" == "darwin"* ]]; then
    DATE_CMD="date -u +%Y%m%d%H%M%S"
else
    DATE_CMD="date -u --iso-8601=seconds | sed 's/[:-]//g' | sed 's/T.*//'"
fi


filename=$(mktemp "${SCRIPT_DIR}/search-results/$($DATE_CMD)-XXXXXXXX.txt")
cd ../wpt
echo "$@" > $filename
echo "------" >> $filename
git grep $@ -- \
  ':(exclude)tools' \
  ':(exclude)conformance-checkers' \
  ':(exclude)docs' \
  ':(exclude)*.min.js' \
  ':(exclude)*-ref.*' \
  ':(exclude)*-notref.*' >> $filename

cat $filename > ${filename}-orig

vim $filename
