#!/usr/bin/env python3

import csv
import os
import re
import subprocess
import sys
import yaml

progress_filepath=os.path.join(os.path.dirname(os.path.realpath(__file__)), 'progress.csv')

def read_classifiers(source):
    with open(source, 'r') as handle:
        return yaml.safe_load(handle)['features']

def compile_file_pattern(source):
    if source.startswith('!'):
        bias = False
        string = source[1:]
    else:
        bias = True
        string = source

    return bias, source, re.compile('^' + re.sub('\\*', '.*', string) + '$')

def expand_classifier(directory, classifier):
    included = []
    excluded = []

    if classifier['files'] == '**':
        for dirpath, dirname, filenames in os.walk(directory):
            included.extend(map(lambda filename: os.path.join(dirpath, filename), filenames))
    else:
        patterns = [
            compile_file_pattern(file_pattern) for file_pattern in classifier['files']
        ]
        used = set()

        for direntry in os.scandir(directory):
            if not direntry.is_file():
                continue
            should_include = False

            for pattern_desc in patterns:
                bias, source, pattern = pattern_desc
                if pattern.search(direntry.name):
                    should_include = bias
                    used.add(source)

            if should_include:
                included.append(os.path.join(directory, direntry))
            else:
                excluded.append(os.path.join(directory, direntry))

        unused = set(classifier['files']).difference(used)
        if unused:
            raise Exception(f'Unused pattern(s) for "{classifier["name"]}": {", ".join(unused)}')

    return { 'included': included, 'excluded': excluded }

def name_from_id(feature_id):
    with open(progress_filepath, 'r') as progress_file:
        reader = csv.reader(progress_file)
        for row in reader:
            if row[0] == feature_id:
                return row[1]
        raise Exception(f'Unrecognized feature ID: "{feature_id}"')

def git(*args):
    return subprocess.run(
        ['git', *args],
        stdout=subprocess.PIPE,
        text=True,
        check=True
    )

def infer_feature_id(stdout):
    ids = set(re.findall('^\+\s*- name:\s*(.*)$', stdout, re.MULTILINE))
    assert len(ids) == 1, f'Expected exactly one feature ID, found {len(ids)}: {ids}'
    return ids.pop()

def main():
    feature_id = infer_feature_id(git('diff', '--staged', '--unified=0').stdout)
    included = []
    excluded = []

    for dirpath, dirnames, filenames in os.walk('.'):
        if 'WEB_FEATURES.yml' not in filenames:
            continue

        classifiers = read_classifiers(os.path.join(dirpath, 'WEB_FEATURES.yml'))

        for classifier in classifiers:
            if classifier['name'] != feature_id:
                continue

            expanded = expand_classifier(dirpath, classifier)
            included.extend(expanded['included'])
            excluded.extend(expanded['excluded'])

    feature_name = name_from_id(feature_id)
    assert len(included) > 0

    git('commit', '-m', f'Map "{feature_name}" to web-features')

if __name__ == '__main__':
    main()
