#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

search_slug=$(echo "$@" | sed -e 's/[^A-Za-z0-9-]/_/g')
filename="${SCRIPT_DIR}/search-results/$(date +%Y-%m-%dT%H:%M:%S)-${search_slug}.txt"

grep_command="git grep $(printf "%q " "$@") -- \
  ':(exclude)tools' \
  ':(exclude)conformance-checkers' \
  ':(exclude)docs' \
  ':(exclude)infrastructure' \
  ':(exclude)*.min.js' \
  ':(exclude)*-ref.*' \
  ':(exclude)*-notref.*'"

echo $grep_command > $filename
bash -c "$grep_command" >> $filename

cat $filename >> ${filename}-orig

vim $filename
