#!/usr/bin/env bash
# Search for web feature references in WPT
# Based on https://github.com/bocoup/wpt-classification-tools/blob/main/wpt-search
#
# Usage: ./wpt-search <feature-name> <search-term>
# Example: ./wpt-search z-index "propdef-z-index"
#
# All search results for a feature will be saved in:
# search-results/<feature-name>/<timestamp>-<sanitized-search-term>.txt

set -eu

if [ $# -lt 2 ]; then
    echo "Usage: $0 <feature-name> <search-term>" >&2
    echo "Example: $0 z-index 'propdef-z-index'" >&2
    exit 1
fi

search_slug=$(echo "$@" | sed -e 's/[^A-Za-z0-9-]/_/g')
if [[ $OSTYPE == "msys" ]]; then
  # Windows OS hates : in the filename
  datestr=$(date +%Y-%m-%dT%H%M%S)
else
  datestr=$(date +%Y-%m-%dT%H:%M:%S)
fi
filename="${SCRIPT_DIR}/search-results/$datestr-${search_slug}.txt"

grep_command="git grep $(printf "%q " "$@") -- \
  ':(exclude)tools' \
  ':(exclude)conformance-checkers' \
  ':(exclude)docs' \
  ':(exclude)infrastructure' \
  ':(exclude)*.min.js' \
  ':(exclude)*-ref.*' \
  ':(exclude)*-notref.*'"

echo $grep_command > $filename
bash -c "$grep_command" >> $filename

cat $filename >> ${filename}-orig

$EDITOR $filename
